version: '3'
name: SmartCityLab-Frontend
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "12312:12312"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
